version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DBNAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
  auth:
    build: .
    restart: always
    environment:
      - DB_DBNAME=${DB_DBNAME}
      - PORT=${PORT}
      - DEBUG=True
      - DB_HOST=db
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
