version: "3.9"

services:
  front:
    image: front
    environment:
      - PORT=${FRONT_PORT}
      - DEBUG=${DEBUG}
    volumes:
      - C:/dev/flask/front/static/:/app/static/
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_USER=${USER}
      - POSTGRES_DB=${DB}
  auth:
    build: .
    restart: always
    environment:
      - CLIENT_SECRET=${CLIENT_SECRET}
      - CLIENT_ID=${CLIENT_ID}
      - SECRET=${AUTH_SECRET}
      - PORT=${AUTH_PORT}
      - DB_DBNAME=${DB}
      - DEBUG=${DEBUG}
      - DB_HOST=db
    volumes:
      - ./:/app/
    depends_on:
      - db
  api:
    image: dmitriyvasil1986/docker-api:latest
    restart: always
    environment:
      - KNOX_AUTH_HOST=http://auth:8000/auth/accounts/
      - SECRET=${API_SECRET}
      - PORT=${API_PORT}
      - DB_DBNAME=${DB}
      - DEBUG=${DEBUG}
      - DB_HOST=db
    depends_on:
      - db
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
